
export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING'
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR'



export const LOGOUT_USER_PENDING = 'App/LOGOUT_USER_PENDING'
export const LOGOUT_USER_SUCCESS = 'App/LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_ERROR = 'App/LOGOUT_USER_ERROR'

export const FORM_RESET = 'redux-form/RESET'

export const SIGNUP_USER_PENDING = 'APP/SIGNUP_USER_PENDING'
export const SIGNUP_USER_SUCCESS = 'APP/SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR = 'APP/SIGNUP_USER_ERROR'

export const SET_USER_PASSWORD_PENDING = 'APP/SET_USER_PASSWORD_PENDING'
export const SET_USER_PASSWORD_SUCCESS = 'APP/SET_USER_PASSWORD_SUCCESS'
export const SET_USER_PASSWORD_ERROR = 'APP/SET_USER_PASSWORD_ERROR'


export const UPDATE_USER_PENDING = 'APP/UPDATE_USER_PENDING'
export const UPDATE_USER_SUCCESS = 'APP/UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'APP/UPDATE_USER_ERROR'


export const ACCESS_TOKEN_REFRESH_PENDING = 'APP/ACCESS_TOKEN_REFRESH_PENDING'
export const ACCESS_TOKEN_REFRESH_SUCCESS = 'APP/ACCESS_TOKEN_REFRESH_SUCCESS'
export const ACCESS_TOKEN_REFRESH_ERROR = 'APP/ACCESS_TOKEN_REFRESH_ERROR'

