export const LOGIN_USER_SUCCESS = "App/LOGIN_USER_SUCCESS";

export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS"

export const SHOW = "SHOW";
export const HIDE = "HIDE";

export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS"